### ISSUE TITLE
How can we run this

### ISSUE THREAD

**Issue by chitrakshbotwala** [avikeid2007/Covidonus#14]
Sir,
How can we run the app on our local machine?

**Comment by avikeid2007** [comment]
Did you have uno platform development environment with visual studio in your local machine?

**Comment by chitrakshbotwala** [comment]
I may install them ? Then what are the steps sir

**Comment by avikeid2007** [comment]
Do you want to just run this app then I will provide you its bundle file? otherwise, to contribute to this project, You have to Install Xamarin & [Uno platform](https://platform.uno/docs/articles/getting-started-tutorial-1.html) development environment in your visual studio.

**Comment by chitrakshbotwala** [comment]
> Do you want to just run this app then I will provide you its bundle file? otherwise, to contribute to this project, You have to Install Xamarin & [Uno platform](https://platform.uno/docs/articles/getting-started-tutorial-1.html) development environment in your visual studio.

I just want to run the app :)

**Comment by avikeid2007** [comment]
try these steps: https://github.com/avikeid2007/Covidonus/releases/tag/1.0.3
